
const dummyTableNames = {
    'users': [
        { name: 'user_id', type: 'int' },
        { name: 'role_id', type: 'int' },
        { name: 'first_name', type: 'varchar' },
        { name: 'last_name', type: 'varchar' },
        { name: 'title', type: 'varchar' },
        { name: 'department', type: 'varchar' },
        { name: 'active', type: 'enum' },
        { name: 'reset_password', type: 'enum' },
        { name: 'email', type: 'varchar' },
        { name: 'time_zone', type: 'varchar' },
        { name: 'phone_no', type: 'varchar' },
        { name: 'location', type: 'varchar' },
        { name: 'user_type', type: 'enum' },
    ],
    'email_log': [
        { name: 'email_log_id', type: 'int' },
        { name: 'event', type: 'int' },
        { name: 'date', type: 'datetime' },
        { name: 'from_address', type: 'varchar' },
        { name: 'to_address', type: 'varchar' },
        { name: 'tags', type: 'varchar' },
        { name: 'body', type: 'varchar' },
        { name: 'status', type: 'enum' },
        { name: 'cc', type: 'varchar' },
        { name: 'bcc', type: 'varchar' },
        { name: 'last_updated', type: 'datetime' },
        { name: 'subject', type: 'varchar' },
        { name: 'message_id', type: 'varchar' },
        { name: 'email_logcol', type: 'varchar' },
    ],
    'cmdb': [
        { name: 'item_name', type: 'varchar' },
        { name: 'item_tag', type: 'varchar' },
        { name: 'item_description', type: 'varchar' },
        { name: 'company', type: 'varchar' },
        { name: 'serial_number', type: 'varchar' },
        { name: 'model_number', type: 'varchar' },
        { name: 'operating_system', type: 'varchar' },
        { name: 'os_domain', type: 'varchar' },
        { name: 'version', type: 'varchar' },
        { name: 'service_pack', type: 'varchar' },
        { name: 'storage', type: 'varchar' },
        { name: 'manufacturer', type: 'varchar' },
        { name: 'relationship_id', type: 'varchar' },
    ],
    'company': [
        { name: 'company_id', type: 'int' },
        { name: 'company_name', type: 'varchar' },
        { name: 'street', type: 'varchar' },
        { name: 'city', type: 'varchar' },
        { name: 'state', type: 'varchar' },
        { name: 'postal_ocde', type: 'varchar' },
        { name: 'phone_no', type: 'varchar' },
        { name: 'fax_no', type: 'varchar' },
        { name: 'currency', type: 'varchar' },
    ],
    'connections': [
        { name: 'id', type: 'int' },
        { name: 'name', type: 'varchar' },
        { name: 'type', type: 'datetime' },
        { name: 'description', type: 'varchar' },
        { name: 'end_point', type: 'varchar' },
        { name: 'authentication_type', type: 'enum' },
        { name: 'enabled', type: 'enum' },
        { name: 'created_at', type: 'datetime' },
        { name: 'last_updated_at', type: 'datetime' },
        { name: 'user', type: 'varchar' },
        { name: 'status', type: 'enum' },
        { name: 'notes', type: 'varchar' },
        { name: 'integration_type', type: 'varchar' },
        { name: 'frequency', type: 'int' },
        { name: 'connection_parameter', type: 'varchar' },
        { name: 'who_can_access', type: 'varchar' },
        { name: 'timeout', type: 'datetime' },
        { name: 'cost', type: 'int' },
        { name: 'version', type: 'varchar' },
        { name: 'source', type: 'varchar' },
        { name: 'created_by', type: 'varchar' },
        { name: 'expiration_policy', type: 'varchar' },
        { name: 'connection_secret', type: 'varchar' },
        { name: 'user_name', type: 'varchar' },
        { name: 'password', type: 'varchar' },
        { name: 'attachment', type: 'varchar' },
        { name: 'source_path', type: 'varchar' },
    ],
    'core_transactions': [
        { name: 'transaction_id', type: 'int' },
        { name: 'user_id', type: 'int' },
        { name: 'first_name', type: 'varchar' },
        { name: 'last_name', type: 'varchar' },
        { name: 'title', type: 'varchar' },
        { name: 'department', type: 'varchar' },
        { name: 'email', type: 'varchar' },
        { name: 'phone_number', type: 'varchar' },
        { name: 'group_id', type: 'int' },
        { name: 'group_name', type: 'varchar' },
        { name: 'group_email', type: 'varchar' },
        { name: 'parent_group', type: 'varchar' },
        { name: 'group_type', type: 'varchar' },
        { name: 'region', type: 'varchar' },
        { name: 'company_id', type: 'int' },
        { name: 'company_name', type: 'varchar' },
        { name: 'role_id', type: 'int' },
        { name: 'role_name', type: 'varchar' },
        { name: 'role_type', type: 'varchar' },
        { name: 'location_id', type: 'int' },
        { name: 'location_name', type: 'varchar' },
        { name: 'postal_code', type: 'int' },
        { name: 'department_id', type: 'int' },
        { name: 'department_name', type: 'varchar' },
        { name: 'manager', type: 'varchar' },
        { name: 'connection_id', type: 'int' },
        { name: 'connection_name', type: 'varchar' },
        { name: 'user', type: 'varchar' },
        { name: 'created_by', type: 'varchar' },
        { name: 'created_date', type: 'datetime' },
        { name: 'last_updated_date', type: 'datetime' },
        { name: 'source_name', type: 'varchar' },
        { name: 'target_name', type: 'varchar' },
        { name: 'contact_person', type: 'varchar' },
    ],
    'document_manager': [
        { name: 'documnet_id', type: 'int' },
        { name: 'document_type', type: 'varchar' },
        { name: 'document_size', type: 'int' },
        { name: 'document_name', type: 'varchar' },
        { name: 'who_can_access', type: 'varchar' },
        { name: 'created_by', type: 'varchar' },
        { name: 'last_modified', type: 'datetime' },
        { name: 'created_date', type: 'datetime' },
        { name: 'description', type: 'varchar' },
    ],
    'feedback': [
        { name: 'feedback_id', type: 'int' },
        { name: 'quetions', type: 'varchar' },
        { name: 'user_id', type: 'int' },
        { name: 'created_date', type: 'datetime' },
        { name: 'updated_date', type: 'datetime' },
        { name: 'deleted', type: 'enum' },
        { name: 'status', type: 'enum' },
        { name: 'created_by', type: 'varchar' },
    ],
    'group_names': [
        { name: 'group_id', type: 'int' },
        { name: 'role_id', type: 'int' },
        { name: 'user_id', type: 'int' },
        { name: 'group_name', type: 'varchar' },
        { name: 'manager_name', type: 'varchar' },
        { name: 'email', type: 'varchar' },
        { name: 'parent_group', type: 'varchar' },
        { name: 'group_type_description', type: 'varchar' },
        { name: 'group_type', type: 'enum' },
        { name: 'region', type: 'varchar' },
    ],
    'location': [
        { name: 'location_id', type: 'int' },
        { name: 'location_name', type: 'varchar' },
        { name: 'street', type: 'varchar' },
        { name: 'city', type: 'varchar' },
        { name: 'state', type: 'varchar' },
        { name: 'postal_code', type: 'varchar' },
        { name: 'contact', type: 'varchar' },
        { name: 'phone_no', type: 'varchar' },
        { name: 'fax_no', type: 'varchar' },
        { name: 'parent_location', type: 'varchar' },
    ],
    'roles': [
        { name: 'role_id', type: 'int' },
        { name: 'role_name', type: 'varchar' },
        { name: 'require_license', type: 'enum' },
        { name: 'description', type: 'varchar' },
        { name: 'role_type', type: 'enum' },
        { name: 'active', type: 'enum' },
        { name: 'extended_roles', type: 'enum' },
    ],
    'service_mapping': [
        { name: 'id', type: 'int' },
        { name: 'department', type: 'varchar' },
        { name: 'category', type: 'varchar' },
        { name: 'sub_category', type: 'varchar' },
        { name: 'service', type: 'varchar' },
        { name: 'manager', type: 'varchar' },
        { name: 'created_by', type: 'varchar' },
        { name: 'last_modified', type: 'datetime' },
        { name: 'status', type: 'enum' },
        { name: 'short_description', type: 'varchar' },
        { name: 'active', type: 'enum' },
    ],
    'sla': [
        { name: 'sla_id', type: 'int' },
        { name: 'sla_name', type: 'varchar' },
        { name: 'start_date', type: 'datetime' },
        { name: 'target_date', type: 'datetime' },
        { name: 'end_date', type: 'datetime' },
        { name: 'duration', type: 'datetime' },
        { name: 'remining_duration', type: 'datetime' },
        { name: 'created_by', type: 'varchar' },
        { name: 'last_modified', type: 'datetime' },
        { name: 'sla_description', type: 'varchar' },
        { name: 'time_format', type: 'int' },
    ],
    'ticket': [
        { name: 'ticket_id', type: 'int' },
        { name: 'ticket_no', type: 'varchar' },
        { name: 'service', type: 'varchar' },
        { name: 'status', type: 'varchar' },
        { name: 'approval_state', type: 'enum' },
        { name: 'short_description', type: 'varchar' },
        { name: 'description', type: 'varchar' },
        { name: 'private_comments', type: 'varchar' },
        { name: 'public_comments', type: 'varchar' },
        { name: 'active', type: 'enum' },
        { name: 'history', type: 'varchar' },
        { name: 'priority', type: 'int' },
        { name: 'requested_email', type: 'varchar' },
        { name: 'department', type: 'varchar' },
        { name: 'state', type: 'varchar' },
        { name: 'assigned_members', type: 'varchar' },
        { name: 'approved_by', type: 'varchar' },
        { name: 'requested_by', type: 'varchar' },
        { name: 'task_type', type: 'varchar' },
    ],

    'department': [
        { name: 'department_id', type: 'int' },
        { name: 'department_name', type: 'varchar' },
        { name: 'description', type: 'varchar' },
        { name: 'manager', type: 'varchar' },
        { name: 'contact_no', type: 'varchar' },
        { name: 'active', type: 'enum' },
    ],
    'ci_transactions': [
        { name: 'ci_transaction_id', type: 'int' },
        { name: 'item_name', type: 'varchar' },
        { name: 'item_tag', type: 'varchar' },
        { name: 'item_description', type: 'varchar' },
        { name: 'company', type: 'varchar' },
        { name: 'serial_number', type: 'varchar' },
        { name: 'model_number', type: 'varchar' },
        { name: 'version', type: 'varchar' },
        { name: 'storage', type: 'varchar' },
        { name: 'operating_system', type: 'varchar' },
        { name: 'os_domain', type: 'varchar' },
        { name: 'service_pack', type: 'varchar' },
        { name: 'manufacturer', type: 'varchar' },
        { name: 'relationship_id', type: 'int' },
    ],
}

export default dummyTableNames