const ConnectionsDummyData = [
    {
        "ID": "1",
        "Name": "API Integration 1",
        "Type": "API",
        "Description": "Integration for data retrieval",
        "Endpoint/Url": "https://api.example.com/data",
        "Authentication Type": "OAuth",
        "Enabled": true,
        "Created At": "2024-04-22T08:00:00Z",
        "Last Updated At": "2024-04-22T08:30:00Z",
        "User/Owner": "John Doe",
        "Status": "active",
        "Notes": "Lorem ipsum dolor sit amet",
        "Integration Type": "Data Retrieval",
        "Frequency": "Hourly",
        "Connection Parameter": [
            443,
            "api_data"
        ],
        "Who can access": ["Admin", "Developer"],
        "Timeout": 30,
        "Cost": 0,
        "Version": "v1.0",
        "Source": "third party API",
        "Created By": "Jane Smith",
        "Expiration Policy": "Never",
        "Connection Secret": "apiSecret123",
        "UserName": "apiUser",
        "Password": "apiPassword123",
        "Attachment": "data_report.pdf",
        "Source Path": "/data_reports"
    },
    {
        "ID": "2",
        "Name": "Database Integration 1",
        "Type": "Database",
        "Description": "Integration for database synchronization",
        "Endpoint/Url": "mysql://db.example.com:3306",
        "Authentication Type": "User/Password",
        "Enabled": true,
        "Created At": "2024-04-21T10:00:00Z",
        "Last Updated At": "2024-04-21T10:15:00Z",
        "User/Owner": "Alice Johnson",
        "Status": "inactive",
        "Notes": "Consectetur adipiscing elit",
        "Integration Type": "Data Sync",
        "Frequency": "Daily",
        "Connection Parameter": [
            3306,
            "sample_db"
        ],
        "Who can access": ["Admin"],
        "Timeout": 60,
        "Cost": 50,
        "Version": "v2.1",
        "Source": "internal system",
        "Created By": "Bob Williams",
        "Expiration Policy": "90 days",
        "Connection Secret": "dbSecret123",
        "UserName": "dbUser",
        "Password": "securePassword",
        "Attachment": "data_backup.zip",
        "Source Path": "/data_backup"
    },
    {
        "ID": "3",
        "Name": "API Integration 2",
        "Type": "API",
        "Description": "Integration for data ingestion",
        "Endpoint/Url": "https://api.example.net/ingest",
        "Authentication Type": "OAuth",
        "Enabled": false,
        "Created At": "2024-04-20T09:00:00Z",
        "Last Updated At": "2024-04-20T09:30:00Z",
        "User/Owner": "Emily Parker",
        "Status": "inactive",
        "Notes": "Sed do eiusmod tempor incididunt",
        "Integration Type": "Data Ingestion",
        "Frequency": "Weekly",
        "Connection Parameter": [
            8080,
            "ingest_data"
        ],
        "Who can access": ["Developer"],
        "Timeout": 45,
        "Cost": 0,
        "Version": "v1.2",
        "Source": "third party API",
        "Created By": "David Brown",
        "Expiration Policy": "180 days",
        "Connection Secret": "ingestSecret456",
        "UserName": "ingestUser",
        "Password": "ingestPassword789",
        "Attachment": "ingest_data.csv",
        "Source Path": "/data_ingest"
    },
    {
        "ID": "4",
        "Name": "File Integration 1",
        "Type": "File",
        "Description": "Integration for file transfer",
        "Endpoint/Url": "ftp://ftp.example.org",
        "Authentication Type": "User/Password",
        "Enabled": true,
        "Created At": "2024-04-19T11:00:00Z",
        "Last Updated At": "2024-04-19T11:15:00Z",
        "User/Owner": "Michael Smith",
        "Status": "active",
        "Notes": "Ut labore et dolore magna aliqua",
        "Integration Type": "File Transfer",
        "Frequency": "Monthly",
        "Connection Parameter": [
            21,
            "file_data"
        ],
        "Who can access": ["Admin", "Manager"],
        "Timeout": 60,
        "Cost": 20,
        "Version": "v3.0",
        "Source": "external database",
        "Created By": "Sophia Taylor",
        "Expiration Policy": "365 days",
        "Connection Secret": "fileSecret789",
        "UserName": "ftpUser",
        "Password": "ftpPassword123",
        "Attachment": "file_data.zip",
        "Source Path": "/file_transfer"
    },
    {
        "ID": "5",
        "Name": "API Integration 3",
        "Type": "API",
        "Description": "Integration for data processing",
        "Endpoint/Url": "https://api.example.org/process",
        "Authentication Type": "OAuth",
        "Enabled": true,
        "Created At": "2024-04-18T12:00:00Z",
        "Last Updated At": "2024-04-18T12:30:00Z",
        "User/Owner": "Ethan Miller",
        "Status": "active",
        "Notes": "Quis nostrud exercitation ullamco",
        "Integration Type": "Data Processing",
        "Frequency": "Daily",
        "Connection Parameter": [
            443,
            "process_data"
        ],
        "Who can access": ["Admin", "Developer"],
        "Timeout": 45,
        "Cost": 0,
        "Version": "v2.5",
        "Source": "third party API",
        "Created By": "Olivia Brown",
        "Expiration Policy": "Never",
        "Connection Secret": "processSecret123",
        "UserName": "processUser",
        "Password": "processPassword456",
        "Attachment": "process_results.csv",
        "Source Path": "/data_process"
    },
    {
        "ID": "6",
        "Name": "Database Integration 2",
        "Type": "Database",
        "Description": "Integration for database reporting",
        "Endpoint/Url": "postgresql://report.example.com:5432",
        "Authentication Type": "User/Password",
        "Enabled": true,
        "Created At": "2024-04-17T13:00:00Z",
        "Last Updated At": "2024-04-17T13:15:00Z",
        "User/Owner": "Natalie Wilson",
        "Status": "active",
        "Notes": "Excepteur sint occaecat cupidatat non proident",
        "Integration Type": "Data Reporting",
        "Frequency": "Weekly",
        "Connection Parameter": [
            5432,
            "report_db"
        ],
        "Who can access": ["Admin", "Manager"],
        "Timeout": 60,
        "Cost": 50,
        "Version": "v1.8",
        "Source": "internal system",
        "Created By": "Liam Johnson",
        "Expiration Policy": "180 days",
        "Connection Secret": "reportSecret456",
        "UserName": "reportUser",
        "Password": "reportPassword789",
        "Attachment": "report_data.xlsx",
        "Source Path": "/data_report"
    },
    {
        "ID": "7",
        "Name": "API Integration 4",
        "Type": "API",
        "Description": "Integration for real-time data",
        "Endpoint/Url": "https://realtimeapi.example.net",
        "Authentication Type": "OAuth",
        "Enabled": false,
        "Created At": "2024-04-16T14:00:00Z",
        "Last Updated At": "2024-04-16T14:30:00Z",
        "User/Owner": "Sophie Harris",
        "Status": "inactive",
        "Notes": "Nemo enim ipsam voluptatem quia voluptas sit aspernatur",
        "Integration Type": "Real-time Data",
        "Frequency": "Hourly",
        "Connection Parameter": [
            443,
            "realtime_data"
        ],
        "Who can access": ["Developer"],
        "Timeout": 30,
        "Cost": 0,
        "Version": "v2.0",
        "Source": "third party API",
        "Created By": "William Martin",
        "Expiration Policy": "90 days",
        "Connection Secret": "realtimeSecret123",
        "UserName": "realtimeUser",
        "Password": "realtimePassword456",
        "Attachment": "realtime_data.json",
        "Source Path": "/data_realtime"
    },
    {
        "ID": "8",
        "Name": "File Integration 2",
        "Type": "File",
        "Description": "Integration for file archiving",
        "Endpoint/Url": "sftp://archive.example.org",
        "Authentication Type": "User/Password",
        "Enabled": true,
        "Created At": "2024-04-15T15:00:00Z",
        "Last Updated At": "2024-04-15T15:15:00Z",
        "User/Owner": "Daniel Clark",
        "Status": "active",
        "Notes": "Voluptatem quia voluptas sit aspernatur aut odit aut fugit",
        "Integration Type": "File Archiving",
        "Frequency": "Monthly",
        "Connection Parameter": [
            22,
            "archive_data"
        ],
        "Who can access": ["Admin", "Manager"],
        "Timeout": 60,
        "Cost": 30,
        "Version": "v1.5",
        "Source": "external database",
        "Created By": "Emma Rodriguez",
        "Expiration Policy": "365 days",
        "Connection Secret": "archiveSecret789",
        "UserName": "archiveUser",
        "Password": "archivePassword123",
        "Attachment": "archive_data.zip",
        "Source Path": "/file_archive"
    },
    {
        "ID": "9",
        "Name": "API Integration 5",
        "Type": "API",
        "Description": "Integration for data analytics",
        "Endpoint/Url": "https://analyticsapi.example.com",
        "Authentication Type": "OAuth",
        "Enabled": true,
        "Created At": "2024-04-14T16:00:00Z",
        "Last Updated At": "2024-04-14T16:30:00Z",
        "User/Owner": "Matthew Turner",
        "Status": "active",
        "Notes": "Sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat",
        "Integration Type": "Data Analytics",
        "Frequency": "Daily",
        "Connection Parameter": [
            443,
            "analytics_data"
        ],
        "Who can access": ["Admin", "Developer"],
        "Timeout": 45,
        "Cost": 0,
        "Version": "v3.2",
        "Source": "third party API",
        "Created By": "Noah Evans",
        "Expiration Policy": "Never",
        "Connection Secret": "analyticsSecret123",
        "UserName": "analyticsUser",
        "Password": "analyticsPassword456",
        "Attachment": "analytics_results.csv",
        "Source Path": "/data_analytics"
    },
    {
        "ID": "10",
        "Name": "Database Integration 3",
        "Type": "Database",
        "Description": "Integration for database backup",
        "Endpoint/Url": "mongodb://backup.example.com:27017",
        "Authentication Type": "User/Password",
        "Enabled": false,
        "Created At": "2024-04-13T17:00:00Z",
        "Last Updated At": "2024-04-13T17:15:00Z",
        "User/Owner": "Oliver Carter",
        "Status": "inactive",
        "Notes": "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae",
        "Integration Type": "Data Backup",
        "Frequency": "Weekly",
        "Connection Parameter": [
            27017,
            "backup_data"
        ],
        "Who can access": ["Admin"],
        "Timeout": 60,
        "Cost": 50,
        "Version": "v2.0",
        "Source": "internal system",
        "Created By": "Isabella Lopez",
        "Expiration Policy": "180 days",
        "Connection Secret": "backupSecret789",
        "UserName": "backupUser",
        "Password": "backupPassword123",
        "Attachment": "backup_data.zip",
        "Source Path": "/data_backup"
    },
    {
        "ID": "11",
        "Name": "API Integration 6",
        "Type": "API",
        "Description": "Integration for data visualization",
        "Endpoint/Url": "https://visualizationapi.example.net",
        "Authentication Type": "OAuth",
        "Enabled": true,
        "Created At": "2024-04-12T18:00:00Z",
        "Last Updated At": "2024-04-12T18:30:00Z",
        "User/Owner": "Ava Stewart",
        "Status": "active",
        "Notes": "Itaque earum rerum hic tenetur a sapiente delectus",
        "Integration Type": "Data Visualization",
        "Frequency": "Hourly",
        "Connection Parameter": [
            443,
            "visualization_data"
        ],
        "Who can access": ["Admin", "Developer"],
        "Timeout": 30,
        "Cost": 0,
        "Version": "v1.0",
        "Source": "third party API",
        "Created By": "Mia Martinez",
        "Expiration Policy": "Never",
        "Connection Secret": "visualizationSecret123",
        "UserName": "visualizationUser",
        "Password": "visualizationPassword456",
        "Attachment": "visualization_results.csv",
        "Source Path": "/data_visualization"
    },
    {
        "ID": "12",
        "Name": "File Integration 3",
        "Type": "File",
        "Description": "Integration for file sharing",
        "Endpoint/Url": "https://share.example.org",
        "Authentication Type": "OAuth",
        "Enabled": true,
        "Created At": "2024-04-11T19:00:00Z",
        "Last Updated At": "2024-04-11T19:15:00Z",
        "User/Owner": "Lucas Bell",
        "Status": "active",
        "Notes": "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus",
        "Integration Type": "File Sharing",
        "Frequency": "Monthly",
        "Connection Parameter": [
            443,
            "share_data"
        ],
        "Who can access": ["Admin", "Manager"],
        "Timeout": 60,
        "Cost": 20,
        "Version": "v2.0",
        "Source": "external database",
        "Created By": "Jack Lee",
        "Expiration Policy": "365 days",
        "Connection Secret": "shareSecret123",
        "UserName": "shareUser",
        "Password": "sharePassword789",
        "Attachment": "shared_file.txt",
        "Source Path": "/file_share"
    },
    {
        "ID": "13",
        "Name": "API Integration 7",
        "Type": "API",
        "Description": "Integration for data transformation",
        "Endpoint/Url": "https://transformapi.example.com",
        "Authentication Type": "OAuth",
        "Enabled": false,
        "Created At": "2024-04-10T20:00:00Z",
        "Last Updated At": "2024-04-10T20:30:00Z",
        "User/Owner": "Charlotte Green",
        "Status": "inactive",
        "Notes": "Omnis voluptas assumenda est, omnis dolor repellendus",
        "Integration Type": "Data Transformation",
        "Frequency": "Weekly",
        "Connection Parameter": [
            443,
            "transform_data"
        ],
        "Who can access": ["Developer"],
        "Timeout": 30,
        "Cost": 0,
        "Version": "v1.2",
        "Source": "third party API",
        "Created By": "Liam Wilson",
        "Expiration Policy": "90 days",
        "Connection Secret": "transformSecret123",
        "UserName": "transformUser",
        "Password": "transformPassword456",
        "Attachment": "transformed_data.csv",
        "Source Path": "/data_transform"
    },
    {
        "ID": "14",
        "Name": "Database Integration 4",
        "Type": "Database",
        "Description": "Integration for database migration",
        "Endpoint/Url": "sqlserver://migration.example.com:1433",
        "Authentication Type": "User/Password",
        "Enabled": true,
        "Created At": "2024-04-09T21:00:00Z",
        "Last Updated At": "2024-04-09T21:15:00Z",
        "User/Owner": "Harper Phillips",
        "Status": "active",
        "Notes": "Repellat autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae",
        "Integration Type": "Data Migration",
        "Frequency": "Daily",
        "Connection Parameter": [
            1433,
            "migration_data"
        ],
        "Who can access": ["Admin", "Manager"],
        "Timeout": 60,
        "Cost": 50,
        "Version": "v2.0",
        "Source": "internal system",
        "Created By": "Ella Roberts",
        "Expiration Policy": "180 days",
        "Connection Secret": "migrationSecret789",
        "UserName": "migrationUser",
        "Password": "migrationPassword123",
        "Attachment": "migration_script.sql",
        "Source Path": "/data_migration"
    },
    {
        "ID": "15",
        "Name": "File Integration 4",
        "Type": "File",
        "Description": "Integration for file conversion",
        "Endpoint/Url": "https://convert.example.org",
        "Authentication Type": "User/Password",
        "Enabled": true,
        "Created At": "2024-04-08T22:00:00Z",
        "Last Updated At": "2024-04-08T22:15:00Z",
        "User/Owner": "Mason Ward",
        "Status": "active",
        "Notes": "Itaque earum rerum hic tenetur a sapiente delectus",
        "Integration Type": "File Conversion",
        "Frequency": "Monthly",
        "Connection Parameter": [
            443,
            "convert_data"
        ],
        "Who can access": ["Admin", "Developer"],
        "Timeout": 60,
        "Cost": 30,
        "Version": "v1.5",
        "Source": "external database",
        "Created By": "Ethan Harris",
        "Expiration Policy": "365 days",
        "Connection Secret": "convertSecret123",
        "UserName": "convertUser",
        "Password": "convertPassword456",
        "Attachment": "converted_file.txt",
        "Source Path": "/file_conversion"
    }
]

export default ConnectionsDummyData