import { set } from "date-fns";
import React from "react";

const WonContext = React.createContext({
    sideNavScrollPosition: 8,
    activeUserData: {},
    isDarkTheme: false,
    userType: 'user',
    openSettings: false,
    openInbox: false,
    activeOption: localStorage.getItem('activeNav'),
    activeAdminOption: localStorage.getItem('activeAdminOpt'),
    sendMail: false,
    showAdminOptions: false,
    recordsPerPage: 10,
    designPreviewData: [],
    nodes: [],
    edges: [],
    activeFlowData: [],
    newEmailRecords: [],
    newIncommingEmails: [],
    triggerFlows: [],
    ip: null,
    showalert: false,
    alertContent: '',
    selectedTheme: 'wonhub',

    usersActiveTab: 1,
    userThemesOpen: false,
    isChatBotOpen: false,
    isReceiverChatOpen: false,
    isSenderChatOpen: false,
    chatData: [],
    istransferTicketOpen: false,
    readEmails: [],
    userCart: [],
    searchInputForArticles: "",
    selectedDesign: null,

    setSideNavScrollPosition: () => { },
    setActiveUserData: () => { },
    removeRole: () => { },
    updateUserType: () => { },
    changeActivetab: () => { },
    OnSetActiveAdminOption: () => { },
    toggleSettings: () => { },
    setUser: () => { },
    setOpenMail: () => { },
    setOpenInbox: () => { },
    toggleAdminOptions: () => { },
    onChangeRecordsPageRecords: () => { },
    updateDesingPreviewData: () => { },
    updateNodes: () => { },
    onNodesChange: () => { },
    addNode: () => { },
    onConnect: () => { },
    onEdgesChange: () => { },
    setactiveFlowData: () => { },
    setShowAlert: () => { },
    setAlertContent: () => { },
    setSelectedTheme: () => { },

    ChangeUserActivetab: () => { },
    openUserThemes: () => { },
    setChatBot: () => { },
    setReceiverChatOpen: () => { },
    setSenderChatOpen: () => { },
    setChatData: () => { },
    setTransferTicketOpen: () => { },
    setReadEmails: () => { },
    setNewEmailRecords: () => { },
    setFlowsTrigger: () => { },
    setUserCart: () => { },
    setSearchInputForArticles: () => { },
    setSelectedDesign: () => { }
})

export default WonContext